Updates the logic to infer a username for configuring dotfiles
freedomofpress/FingerprintSecureDrop pull request #52
Opened 2016-09-22 23:40 UTC by conorsch

We can't assume that `ansible_ssh_user` will be defined, since it's not
populated by default in Ansible. When provisioning Vagrant VMs, the
`ansible_ssh_user` var is defined because it's hardcoded in the static
inventory file that Vagrant generates.

Let's prefer `ansible_user`, which supersedes `ansible_ssh_user` as of v2,
but still honor `ansible_ssh_user` to support Vagrant. If neither can be
found, we'll fall back to using the username of the account running
ansible on the Ansible controller.

2016-09-22 23:40 UTC, conorsch commented
Extremely minor changes here—#51 describes a more durable solution, but the changes proposed here work on both prod servers and vagrant VMs.

2016-09-23 20:26 UTC, psivesely requested changes
This seems like a good way to handle . Can you update to include the `fpsd_database_username` in `roles/default/database/defaults/main.yml`?

2016-09-23 20:26 UTC, fowlslegs commented
handle this*.

2016-09-26 18:11 UTC, conorsch commented
Updated the username var in the database role and amended the commit.

2016-09-26 23:41 UTC, conorsch commented
Closes #32.

2016-10-11 17:46 UTC, merged